---
 apiVersion: v1
 kind: Pod
 metadata:
   name: rss-site
   labels:
     app: web
 spec:
   containers:
     - name: front-end
       image: nginx/nginx-alpine
       ports:
         - containerPort: 80
     - name: rss-reader
       image: nginxdemos/hello
       ports:
         - containerPort: 88
